### ISSUE TITLE
Fails to install with distutils 59.1.0

### ISSUE THREAD

**Issue by nijel** [Nekmo/python-akismet#15]
### Description

Installation fails with distutils 59.1.0:

```pytb
   Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2zi1n0lu/python-akismet_915ecaab43fa40119c0ad12ce5d89261/setup.py", line 280, in <module>
      setup(
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
Error:       raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
```

This is already fixed in https://github.com/Nekmo/python-akismet/commit/13e45026ce618ae68c6e9d030d0e2393c6ac65b5, but not yet released to PyPI...

### What I Did

```
pip install python-akismet
```

### See Also

https://github.com/pypa/setuptools/pull/2870

**Comment by Nekmo** [comment]
Uploaded! https://pypi.org/project/python-akismet/
